#!/usr/bin/env php
<?php

// Incluimos autocargador de Composer
require __DIR__ . '/vendor/autoload.php';

// Imprimimos titulo
echo "\e[43;30;5m                                                                                         \e[0m\n";
echo "\e[43;30;5m  Armazón - Marco de Trabajo y Servidor de Aplicación de Alto Rendimiento y Flexibilidad \e[0m\n";
echo "\e[43;30;5m                                                                                         \e[0m\n";
echo "\n";


if (isset($argv[1]) && $argv[1] == 'iniciar') {

    // Obtenemos instancia de la aplicación
    $app = require 'app/instancia.php';

    // Instanciamos servidor Swoole
    $servidor = new Armazon\Servidor\Swoole($app);

    // Configuramos servidor
    $servidor->archivoPid = '/var/run/armazon.pid';
    $servidor->archivoRegistros = '/var/log/armazon.log';

    // Corremos el servidor
    $servidor->iniciar();

} else {

    echo "Comandos disponibles:\n";
    echo "\n";
    echo " > iniciar\n";
    echo " > detener\n";
    echo "\n";

}
