<!DOCTYPE html>
<html lang="{{idioma}}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{v|e|titulo}} - Armazón</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">

    <!-- ESTILOS DE VISTA -->
    <?php
    if (isset($this->css)) {
        foreach ($this->css as $css) {
            echo "    <link rel=\"stylesheet\" href=\"{$css}\">\n";
        }
    }
    ?>
</head>

<body style="padding-top: 50px;">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Armazón</a>
        </div>

        <div id="navbar" class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li class="active"><a href="">Inicio</a></li>
                <li><a href="">Quienes Somos</a></li>
                <li><a href="">Contacto</a></li>
            </ul>
        </div>
    </div>
</nav>

<div id="contenido" class="container">
<!-- INICIA CONTENIDO DE VISTA -->
<?= $this->contenido ?>
<!-- TERMINA CONTENIDO DE VISTA -->
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" crossorigin="anonymous"></script>
<!-- SCRIPTS DE VISTA -->*
<?php
if (isset($this->js)) {
    foreach ($this->js as $js) {
        echo "<script src=\"{$js}\"></script>\n";
    }
}
?>

</body>
</html>
